name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: najiibmohamed11
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: "blue"
          color_dots: "000000,000000,000000,000000,000000"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
